manifest:
  remotes:
    - name: srwooten2
      url-base: https://github.com/srwooten2
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
